import { UpdateUserMembershipStatusData, UpdateUserMembershipStatusVariables, DeleteUserData, DeleteUserVariables, CreateUserData, CreateUserVariables, CreateUserGroupAdminData, CreateUserGroupAdminVariables, AddUserToUserGroupAdminData, AddUserToUserGroupAdminVariables, RemoveUserFromUserGroupAdminData, RemoveUserFromUserGroupAdminVariables, GetUserGroupByNameData, GetUserGroupByNameVariables, GetUserUserGroupsForAdminData, GetUserUserGroupsForAdminVariables, GetUserForCheckoutData, GetUserForCheckoutVariables, GetTicketTypeForCheckoutData, GetTicketTypeForCheckoutVariables, UpdateUserStripeCustomerIdData, UpdateUserStripeCustomerIdVariables, GetEventByIdForCallableData, GetEventByIdForCallableVariables, GetSectionByIdForCallableData, GetSectionByIdForCallableVariables, GetBookingsForBookerAndEventData, GetBookingsForBookerAndEventVariables, GetTicketOrdersForBookerAndEventData, GetTicketOrdersForBookerAndEventVariables, CreateBookingDraftForUserData, CreateBookingDraftForUserVariables, CreateBookingDraftRevisionForUserData, CreateBookingDraftRevisionForUserVariables, MarkBookingSupersededFromCallableData, MarkBookingSupersededFromCallableVariables, CreateBookingPaymentAdjustmentFromCallableData, CreateBookingPaymentAdjustmentFromCallableVariables, AddBookingLineFromCallableData, AddBookingLineFromCallableVariables, UpdateBookingStatusFromCallableData, UpdateBookingStatusFromCallableVariables, CreateTicketOrderForCheckoutData, CreateTicketOrderForCheckoutVariables, GetTicketOrderForWebhookData, GetTicketOrderForWebhookVariables, GetTicketOrderStripeArtifactsForCallableData, GetTicketOrderStripeArtifactsForCallableVariables, GetPaymentWebhookEventByStripeEventIdData, GetPaymentWebhookEventByStripeEventIdVariables, CreatePaymentWebhookEventData, CreatePaymentWebhookEventVariables, GetNotificationDeliveryByChannelAndKeyData, GetNotificationDeliveryByChannelAndKeyVariables, ListFailedNotificationDeliveriesForRecoveryData, ListFailedNotificationDeliveriesForRecoveryVariables, ListStalePendingNotificationDeliveriesForRecoveryData, ListStalePendingNotificationDeliveriesForRecoveryVariables, CreateNotificationDeliveryData, CreateNotificationDeliveryVariables, ClaimNotificationDeliveryByIdData, ClaimNotificationDeliveryByIdVariables, RecordNotificationRecoveryFailureByIdData, RecordNotificationRecoveryFailureByIdVariables, MarkNotificationDeliverySentByIdData, MarkNotificationDeliverySentByIdVariables, MarkNotificationDeliveryFailedByIdData, MarkNotificationDeliveryFailedByIdVariables, MarkTicketOrderPaidFromWebhookData, MarkTicketOrderPaidFromWebhookVariables, MarkTicketOrderFailedFromWebhookData, MarkTicketOrderFailedFromWebhookVariables, MarkTicketOrderRefundedFromWebhookData, MarkTicketOrderRefundedFromWebhookVariables, UpsertTicketOrderDisputeFromWebhookData, UpsertTicketOrderDisputeFromWebhookVariables, GetPaymentReconciliationExceptionByOrderAndTypeData, GetPaymentReconciliationExceptionByOrderAndTypeVariables, UpsertPaymentReconciliationExceptionData, UpsertPaymentReconciliationExceptionVariables, UpdateBookingPreferencesFromCallableData, UpdateBookingPreferencesFromCallableVariables, DeleteBookingLineFromCallableData, DeleteBookingLineFromCallableVariables, CreateGuestTicketRequestFromCallableData, CreateGuestTicketRequestFromCallableVariables, AdminReviewGuestTicketRequestFromCallableData, AdminReviewGuestTicketRequestFromCallableVariables, GetBookingForGuestTicketCallableData, GetBookingForGuestTicketCallableVariables, GetBookingForNotificationData, GetBookingForNotificationVariables, ListStaleDraftBookingsForSchedulerData, ListStaleDraftBookingsForSchedulerVariables, ListStalePendingTicketOrdersForSchedulerData, ListStalePendingTicketOrdersForSchedulerVariables, GetGuestTicketRequestForNotificationData, GetGuestTicketRequestForNotificationVariables, GetSectionAnnouncementOptOutsData, GetSectionAnnouncementOptOutsVariables, CreateAnnouncementSendData, CreateAnnouncementSendVariables, CreateAnnouncementRecipientData, CreateAnnouncementRecipientVariables, GetAnnouncementRecipientCountData, GetAnnouncementRecipientCountVariables, GetAnnouncementSendHistoryData, GetAnnouncementSendHistoryVariables, GetAnnouncementSendRecipientsData, GetAnnouncementSendRecipientsVariables, GetAnnouncementSendByIdData, GetAnnouncementSendByIdVariables, GetAnnouncementRecipientBySendAndUserData, GetAnnouncementRecipientBySendAndUserVariables, TryUpdateAnnouncementRecipientDeliveryStatusData, TryUpdateAnnouncementRecipientDeliveryStatusVariables, GetUserByEmailData, GetUserByEmailVariables, GetNotifyCallbackUserByIdData, GetNotifyCallbackUserByIdVariables, TryApplyNotifyDeliveryUserStateData, TryApplyNotifyDeliveryUserStateVariables, TryApplyNotifyDeliveryUserStateAndMarkLostData, TryApplyNotifyDeliveryUserStateAndMarkLostVariables, GetNotifyDeliveryReceiptData, GetNotifyDeliveryReceiptVariables, CreateNotifyDeliveryReceiptData, CreateNotifyDeliveryReceiptVariables, ClaimNotifyDeliveryReceiptData, ClaimNotifyDeliveryReceiptVariables, MarkNotifyDeliveryReceiptProcessedData, MarkNotifyDeliveryReceiptProcessedVariables, MarkNotifyDeliveryReceiptFailedData, MarkNotifyDeliveryReceiptFailedVariables, GetRecentNotifyDeliveryReceiptsForUserData, GetRecentNotifyDeliveryReceiptsForUserVariables, GetLatestNotifyDeliveryReceiptForReferenceData, GetLatestNotifyDeliveryReceiptForReferenceVariables, AdminOptOutSectionAnnouncementData, AdminOptOutSectionAnnouncementVariables, AdminOptInSectionAnnouncementData, AdminOptInSectionAnnouncementVariables, GetCallableInvocationData, GetCallableInvocationVariables, UpsertCallableInvocationData, UpsertCallableInvocationVariables, EnsureCallableRateLimitBucketData, EnsureCallableRateLimitBucketVariables, ConsumeCallableRateLimitData, ConsumeCallableRateLimitVariables, CreateBookingDraftData, CreateBookingDraftVariables, AddBookingLineData, AddBookingLineVariables, UpdateBookingStatusData, UpdateBookingStatusVariables, CreateGuestTicketRequestData, CreateGuestTicketRequestVariables, AdminDeleteGuestTicketRequestData, AdminDeleteGuestTicketRequestVariables, AdminReviewGuestTicketRequestData, AdminReviewGuestTicketRequestVariables, AdminDeleteBookingLineData, AdminDeleteBookingLineVariables, AdminDeleteBookingData, AdminDeleteBookingVariables, ResolvePaymentReconciliationExceptionData, ResolvePaymentReconciliationExceptionVariables, GetCurrentUserData, GetUserByIdData, GetUserByIdVariables, ListUsersData, ListSectionsData, GetSectionsForUserData, ListUserGroupsData, GetUserAccessGroupsData, CheckUserProfileExistsData, GetUserMembershipStatusData, GetUserMembershipStatusVariables, GetUserWithAccessGroupsData, GetUserWithAccessGroupsVariables, GetUserAccessGroupsByIdData, GetUserAccessGroupsByIdVariables, GetEventsForSectionData, GetEventsForSectionVariables, GetEventByIdData, GetEventByIdVariables, GetSectionByIdData, GetSectionByIdVariables, GetUserGroupByIdData, GetUserGroupByIdVariables, GetAllUserGroupsWithStatusesData, GetSectionMembersData, GetSectionMembersVariables, GetMyBookingsForEventData, GetMyBookingsForEventVariables, GetMyBookingsData, GetMyTicketOrderByIdData, GetMyTicketOrderByIdVariables, GetMyTicketOrdersData, GetMyBookingPaymentAdjustmentsData, ListEventBookingsForAdminData, ListEventBookingsForAdminVariables, ListGuestTicketRequestsForAdminData, ListGuestTicketRequestsForAdminVariables, ListTicketOrdersForAdminData, ListTicketOrdersForAdminVariables, ListBookingPaymentAdjustmentsForAdminData, ListBookingPaymentAdjustmentsForAdminVariables, ListOpenPaymentReconciliationExceptionsData, GetSectionAnnouncementOptOutData, GetSectionAnnouncementOptOutVariables, GetMyAnnouncementPreferencesData, CreateSectionData, CreateSectionVariables, CreateUserGroupData, CreateUserGroupVariables, AddUserToUserGroupData, AddUserToUserGroupVariables, RemoveUserFromUserGroupData, RemoveUserFromUserGroupVariables, GrantUserGroupToSectionForPurposeData, GrantUserGroupToSectionForPurposeVariables, RevokeUserGroupFromSectionForPurposeData, RevokeUserGroupFromSectionForPurposeVariables, UpdateUserGroupData, UpdateUserGroupVariables, DeleteUserGroupData, DeleteUserGroupVariables, UpdateSectionData, UpdateSectionVariables, DeleteSectionData, DeleteSectionVariables, CreateEventData, CreateEventVariables, UpdateEventData, UpdateEventVariables, DeleteEventData, DeleteEventVariables, CreateTicketTypeData, CreateTicketTypeVariables, UpdateTicketTypeData, UpdateTicketTypeVariables, DeleteTicketTypeData, DeleteTicketTypeVariables, CreateUserProfileData, CreateUserProfileVariables, UpsertUserData, UpsertUserVariables, UpdateUserData, UpdateUserVariables, RegisterForSectionData, RegisterForSectionVariables, UnregisterFromSectionData, UnregisterFromSectionVariables, SubscribeToUserGroupData, SubscribeToUserGroupVariables, UnsubscribeFromUserGroupData, UnsubscribeFromUserGroupVariables, OptOutSectionAnnouncementData, OptOutSectionAnnouncementVariables, OptInSectionAnnouncementData, OptInSectionAnnouncementVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useUpdateUserMembershipStatus(options?: useDataConnectMutationOptions<UpdateUserMembershipStatusData, FirebaseError, UpdateUserMembershipStatusVariables>): UseDataConnectMutationResult<UpdateUserMembershipStatusData, UpdateUserMembershipStatusVariables>;
export function useUpdateUserMembershipStatus(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserMembershipStatusData, FirebaseError, UpdateUserMembershipStatusVariables>): UseDataConnectMutationResult<UpdateUserMembershipStatusData, UpdateUserMembershipStatusVariables>;

export function useDeleteUser(options?: useDataConnectMutationOptions<DeleteUserData, FirebaseError, DeleteUserVariables>): UseDataConnectMutationResult<DeleteUserData, DeleteUserVariables>;
export function useDeleteUser(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteUserData, FirebaseError, DeleteUserVariables>): UseDataConnectMutationResult<DeleteUserData, DeleteUserVariables>;

export function useCreateUser(options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;
export function useCreateUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;

export function useCreateUserGroupAdmin(options?: useDataConnectMutationOptions<CreateUserGroupAdminData, FirebaseError, CreateUserGroupAdminVariables>): UseDataConnectMutationResult<CreateUserGroupAdminData, CreateUserGroupAdminVariables>;
export function useCreateUserGroupAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserGroupAdminData, FirebaseError, CreateUserGroupAdminVariables>): UseDataConnectMutationResult<CreateUserGroupAdminData, CreateUserGroupAdminVariables>;

export function useAddUserToUserGroupAdmin(options?: useDataConnectMutationOptions<AddUserToUserGroupAdminData, FirebaseError, AddUserToUserGroupAdminVariables>): UseDataConnectMutationResult<AddUserToUserGroupAdminData, AddUserToUserGroupAdminVariables>;
export function useAddUserToUserGroupAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<AddUserToUserGroupAdminData, FirebaseError, AddUserToUserGroupAdminVariables>): UseDataConnectMutationResult<AddUserToUserGroupAdminData, AddUserToUserGroupAdminVariables>;

export function useRemoveUserFromUserGroupAdmin(options?: useDataConnectMutationOptions<RemoveUserFromUserGroupAdminData, FirebaseError, RemoveUserFromUserGroupAdminVariables>): UseDataConnectMutationResult<RemoveUserFromUserGroupAdminData, RemoveUserFromUserGroupAdminVariables>;
export function useRemoveUserFromUserGroupAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveUserFromUserGroupAdminData, FirebaseError, RemoveUserFromUserGroupAdminVariables>): UseDataConnectMutationResult<RemoveUserFromUserGroupAdminData, RemoveUserFromUserGroupAdminVariables>;

export function useGetUserGroupByName(vars: GetUserGroupByNameVariables, options?: useDataConnectQueryOptions<GetUserGroupByNameData>): UseDataConnectQueryResult<GetUserGroupByNameData, GetUserGroupByNameVariables>;
export function useGetUserGroupByName(dc: DataConnect, vars: GetUserGroupByNameVariables, options?: useDataConnectQueryOptions<GetUserGroupByNameData>): UseDataConnectQueryResult<GetUserGroupByNameData, GetUserGroupByNameVariables>;

export function useGetUserUserGroupsForAdmin(vars: GetUserUserGroupsForAdminVariables, options?: useDataConnectQueryOptions<GetUserUserGroupsForAdminData>): UseDataConnectQueryResult<GetUserUserGroupsForAdminData, GetUserUserGroupsForAdminVariables>;
export function useGetUserUserGroupsForAdmin(dc: DataConnect, vars: GetUserUserGroupsForAdminVariables, options?: useDataConnectQueryOptions<GetUserUserGroupsForAdminData>): UseDataConnectQueryResult<GetUserUserGroupsForAdminData, GetUserUserGroupsForAdminVariables>;

export function useGetUserForCheckout(vars: GetUserForCheckoutVariables, options?: useDataConnectQueryOptions<GetUserForCheckoutData>): UseDataConnectQueryResult<GetUserForCheckoutData, GetUserForCheckoutVariables>;
export function useGetUserForCheckout(dc: DataConnect, vars: GetUserForCheckoutVariables, options?: useDataConnectQueryOptions<GetUserForCheckoutData>): UseDataConnectQueryResult<GetUserForCheckoutData, GetUserForCheckoutVariables>;

export function useGetTicketTypeForCheckout(vars: GetTicketTypeForCheckoutVariables, options?: useDataConnectQueryOptions<GetTicketTypeForCheckoutData>): UseDataConnectQueryResult<GetTicketTypeForCheckoutData, GetTicketTypeForCheckoutVariables>;
export function useGetTicketTypeForCheckout(dc: DataConnect, vars: GetTicketTypeForCheckoutVariables, options?: useDataConnectQueryOptions<GetTicketTypeForCheckoutData>): UseDataConnectQueryResult<GetTicketTypeForCheckoutData, GetTicketTypeForCheckoutVariables>;

export function useUpdateUserStripeCustomerId(options?: useDataConnectMutationOptions<UpdateUserStripeCustomerIdData, FirebaseError, UpdateUserStripeCustomerIdVariables>): UseDataConnectMutationResult<UpdateUserStripeCustomerIdData, UpdateUserStripeCustomerIdVariables>;
export function useUpdateUserStripeCustomerId(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserStripeCustomerIdData, FirebaseError, UpdateUserStripeCustomerIdVariables>): UseDataConnectMutationResult<UpdateUserStripeCustomerIdData, UpdateUserStripeCustomerIdVariables>;

export function useGetEventByIdForCallable(vars: GetEventByIdForCallableVariables, options?: useDataConnectQueryOptions<GetEventByIdForCallableData>): UseDataConnectQueryResult<GetEventByIdForCallableData, GetEventByIdForCallableVariables>;
export function useGetEventByIdForCallable(dc: DataConnect, vars: GetEventByIdForCallableVariables, options?: useDataConnectQueryOptions<GetEventByIdForCallableData>): UseDataConnectQueryResult<GetEventByIdForCallableData, GetEventByIdForCallableVariables>;

export function useGetSectionByIdForCallable(vars: GetSectionByIdForCallableVariables, options?: useDataConnectQueryOptions<GetSectionByIdForCallableData>): UseDataConnectQueryResult<GetSectionByIdForCallableData, GetSectionByIdForCallableVariables>;
export function useGetSectionByIdForCallable(dc: DataConnect, vars: GetSectionByIdForCallableVariables, options?: useDataConnectQueryOptions<GetSectionByIdForCallableData>): UseDataConnectQueryResult<GetSectionByIdForCallableData, GetSectionByIdForCallableVariables>;

export function useGetBookingsForBookerAndEvent(vars: GetBookingsForBookerAndEventVariables, options?: useDataConnectQueryOptions<GetBookingsForBookerAndEventData>): UseDataConnectQueryResult<GetBookingsForBookerAndEventData, GetBookingsForBookerAndEventVariables>;
export function useGetBookingsForBookerAndEvent(dc: DataConnect, vars: GetBookingsForBookerAndEventVariables, options?: useDataConnectQueryOptions<GetBookingsForBookerAndEventData>): UseDataConnectQueryResult<GetBookingsForBookerAndEventData, GetBookingsForBookerAndEventVariables>;

export function useGetTicketOrdersForBookerAndEvent(vars: GetTicketOrdersForBookerAndEventVariables, options?: useDataConnectQueryOptions<GetTicketOrdersForBookerAndEventData>): UseDataConnectQueryResult<GetTicketOrdersForBookerAndEventData, GetTicketOrdersForBookerAndEventVariables>;
export function useGetTicketOrdersForBookerAndEvent(dc: DataConnect, vars: GetTicketOrdersForBookerAndEventVariables, options?: useDataConnectQueryOptions<GetTicketOrdersForBookerAndEventData>): UseDataConnectQueryResult<GetTicketOrdersForBookerAndEventData, GetTicketOrdersForBookerAndEventVariables>;

export function useCreateBookingDraftForUser(options?: useDataConnectMutationOptions<CreateBookingDraftForUserData, FirebaseError, CreateBookingDraftForUserVariables>): UseDataConnectMutationResult<CreateBookingDraftForUserData, CreateBookingDraftForUserVariables>;
export function useCreateBookingDraftForUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateBookingDraftForUserData, FirebaseError, CreateBookingDraftForUserVariables>): UseDataConnectMutationResult<CreateBookingDraftForUserData, CreateBookingDraftForUserVariables>;

export function useCreateBookingDraftRevisionForUser(options?: useDataConnectMutationOptions<CreateBookingDraftRevisionForUserData, FirebaseError, CreateBookingDraftRevisionForUserVariables>): UseDataConnectMutationResult<CreateBookingDraftRevisionForUserData, CreateBookingDraftRevisionForUserVariables>;
export function useCreateBookingDraftRevisionForUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateBookingDraftRevisionForUserData, FirebaseError, CreateBookingDraftRevisionForUserVariables>): UseDataConnectMutationResult<CreateBookingDraftRevisionForUserData, CreateBookingDraftRevisionForUserVariables>;

export function useMarkBookingSupersededFromCallable(options?: useDataConnectMutationOptions<MarkBookingSupersededFromCallableData, FirebaseError, MarkBookingSupersededFromCallableVariables>): UseDataConnectMutationResult<MarkBookingSupersededFromCallableData, MarkBookingSupersededFromCallableVariables>;
export function useMarkBookingSupersededFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<MarkBookingSupersededFromCallableData, FirebaseError, MarkBookingSupersededFromCallableVariables>): UseDataConnectMutationResult<MarkBookingSupersededFromCallableData, MarkBookingSupersededFromCallableVariables>;

export function useCreateBookingPaymentAdjustmentFromCallable(options?: useDataConnectMutationOptions<CreateBookingPaymentAdjustmentFromCallableData, FirebaseError, CreateBookingPaymentAdjustmentFromCallableVariables>): UseDataConnectMutationResult<CreateBookingPaymentAdjustmentFromCallableData, CreateBookingPaymentAdjustmentFromCallableVariables>;
export function useCreateBookingPaymentAdjustmentFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<CreateBookingPaymentAdjustmentFromCallableData, FirebaseError, CreateBookingPaymentAdjustmentFromCallableVariables>): UseDataConnectMutationResult<CreateBookingPaymentAdjustmentFromCallableData, CreateBookingPaymentAdjustmentFromCallableVariables>;

export function useAddBookingLineFromCallable(options?: useDataConnectMutationOptions<AddBookingLineFromCallableData, FirebaseError, AddBookingLineFromCallableVariables>): UseDataConnectMutationResult<AddBookingLineFromCallableData, AddBookingLineFromCallableVariables>;
export function useAddBookingLineFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<AddBookingLineFromCallableData, FirebaseError, AddBookingLineFromCallableVariables>): UseDataConnectMutationResult<AddBookingLineFromCallableData, AddBookingLineFromCallableVariables>;

export function useUpdateBookingStatusFromCallable(options?: useDataConnectMutationOptions<UpdateBookingStatusFromCallableData, FirebaseError, UpdateBookingStatusFromCallableVariables>): UseDataConnectMutationResult<UpdateBookingStatusFromCallableData, UpdateBookingStatusFromCallableVariables>;
export function useUpdateBookingStatusFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateBookingStatusFromCallableData, FirebaseError, UpdateBookingStatusFromCallableVariables>): UseDataConnectMutationResult<UpdateBookingStatusFromCallableData, UpdateBookingStatusFromCallableVariables>;

export function useCreateTicketOrderForCheckout(options?: useDataConnectMutationOptions<CreateTicketOrderForCheckoutData, FirebaseError, CreateTicketOrderForCheckoutVariables>): UseDataConnectMutationResult<CreateTicketOrderForCheckoutData, CreateTicketOrderForCheckoutVariables>;
export function useCreateTicketOrderForCheckout(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTicketOrderForCheckoutData, FirebaseError, CreateTicketOrderForCheckoutVariables>): UseDataConnectMutationResult<CreateTicketOrderForCheckoutData, CreateTicketOrderForCheckoutVariables>;

export function useGetTicketOrderForWebhook(vars: GetTicketOrderForWebhookVariables, options?: useDataConnectQueryOptions<GetTicketOrderForWebhookData>): UseDataConnectQueryResult<GetTicketOrderForWebhookData, GetTicketOrderForWebhookVariables>;
export function useGetTicketOrderForWebhook(dc: DataConnect, vars: GetTicketOrderForWebhookVariables, options?: useDataConnectQueryOptions<GetTicketOrderForWebhookData>): UseDataConnectQueryResult<GetTicketOrderForWebhookData, GetTicketOrderForWebhookVariables>;

export function useGetTicketOrderStripeArtifactsForCallable(vars: GetTicketOrderStripeArtifactsForCallableVariables, options?: useDataConnectQueryOptions<GetTicketOrderStripeArtifactsForCallableData>): UseDataConnectQueryResult<GetTicketOrderStripeArtifactsForCallableData, GetTicketOrderStripeArtifactsForCallableVariables>;
export function useGetTicketOrderStripeArtifactsForCallable(dc: DataConnect, vars: GetTicketOrderStripeArtifactsForCallableVariables, options?: useDataConnectQueryOptions<GetTicketOrderStripeArtifactsForCallableData>): UseDataConnectQueryResult<GetTicketOrderStripeArtifactsForCallableData, GetTicketOrderStripeArtifactsForCallableVariables>;

export function useGetPaymentWebhookEventByStripeEventId(vars: GetPaymentWebhookEventByStripeEventIdVariables, options?: useDataConnectQueryOptions<GetPaymentWebhookEventByStripeEventIdData>): UseDataConnectQueryResult<GetPaymentWebhookEventByStripeEventIdData, GetPaymentWebhookEventByStripeEventIdVariables>;
export function useGetPaymentWebhookEventByStripeEventId(dc: DataConnect, vars: GetPaymentWebhookEventByStripeEventIdVariables, options?: useDataConnectQueryOptions<GetPaymentWebhookEventByStripeEventIdData>): UseDataConnectQueryResult<GetPaymentWebhookEventByStripeEventIdData, GetPaymentWebhookEventByStripeEventIdVariables>;

export function useCreatePaymentWebhookEvent(options?: useDataConnectMutationOptions<CreatePaymentWebhookEventData, FirebaseError, CreatePaymentWebhookEventVariables>): UseDataConnectMutationResult<CreatePaymentWebhookEventData, CreatePaymentWebhookEventVariables>;
export function useCreatePaymentWebhookEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePaymentWebhookEventData, FirebaseError, CreatePaymentWebhookEventVariables>): UseDataConnectMutationResult<CreatePaymentWebhookEventData, CreatePaymentWebhookEventVariables>;

export function useGetNotificationDeliveryByChannelAndKey(vars: GetNotificationDeliveryByChannelAndKeyVariables, options?: useDataConnectQueryOptions<GetNotificationDeliveryByChannelAndKeyData>): UseDataConnectQueryResult<GetNotificationDeliveryByChannelAndKeyData, GetNotificationDeliveryByChannelAndKeyVariables>;
export function useGetNotificationDeliveryByChannelAndKey(dc: DataConnect, vars: GetNotificationDeliveryByChannelAndKeyVariables, options?: useDataConnectQueryOptions<GetNotificationDeliveryByChannelAndKeyData>): UseDataConnectQueryResult<GetNotificationDeliveryByChannelAndKeyData, GetNotificationDeliveryByChannelAndKeyVariables>;

export function useListFailedNotificationDeliveriesForRecovery(vars: ListFailedNotificationDeliveriesForRecoveryVariables, options?: useDataConnectQueryOptions<ListFailedNotificationDeliveriesForRecoveryData>): UseDataConnectQueryResult<ListFailedNotificationDeliveriesForRecoveryData, ListFailedNotificationDeliveriesForRecoveryVariables>;
export function useListFailedNotificationDeliveriesForRecovery(dc: DataConnect, vars: ListFailedNotificationDeliveriesForRecoveryVariables, options?: useDataConnectQueryOptions<ListFailedNotificationDeliveriesForRecoveryData>): UseDataConnectQueryResult<ListFailedNotificationDeliveriesForRecoveryData, ListFailedNotificationDeliveriesForRecoveryVariables>;

export function useListStalePendingNotificationDeliveriesForRecovery(vars: ListStalePendingNotificationDeliveriesForRecoveryVariables, options?: useDataConnectQueryOptions<ListStalePendingNotificationDeliveriesForRecoveryData>): UseDataConnectQueryResult<ListStalePendingNotificationDeliveriesForRecoveryData, ListStalePendingNotificationDeliveriesForRecoveryVariables>;
export function useListStalePendingNotificationDeliveriesForRecovery(dc: DataConnect, vars: ListStalePendingNotificationDeliveriesForRecoveryVariables, options?: useDataConnectQueryOptions<ListStalePendingNotificationDeliveriesForRecoveryData>): UseDataConnectQueryResult<ListStalePendingNotificationDeliveriesForRecoveryData, ListStalePendingNotificationDeliveriesForRecoveryVariables>;

export function useCreateNotificationDelivery(options?: useDataConnectMutationOptions<CreateNotificationDeliveryData, FirebaseError, CreateNotificationDeliveryVariables>): UseDataConnectMutationResult<CreateNotificationDeliveryData, CreateNotificationDeliveryVariables>;
export function useCreateNotificationDelivery(dc: DataConnect, options?: useDataConnectMutationOptions<CreateNotificationDeliveryData, FirebaseError, CreateNotificationDeliveryVariables>): UseDataConnectMutationResult<CreateNotificationDeliveryData, CreateNotificationDeliveryVariables>;

export function useClaimNotificationDeliveryById(options?: useDataConnectMutationOptions<ClaimNotificationDeliveryByIdData, FirebaseError, ClaimNotificationDeliveryByIdVariables>): UseDataConnectMutationResult<ClaimNotificationDeliveryByIdData, ClaimNotificationDeliveryByIdVariables>;
export function useClaimNotificationDeliveryById(dc: DataConnect, options?: useDataConnectMutationOptions<ClaimNotificationDeliveryByIdData, FirebaseError, ClaimNotificationDeliveryByIdVariables>): UseDataConnectMutationResult<ClaimNotificationDeliveryByIdData, ClaimNotificationDeliveryByIdVariables>;

export function useRecordNotificationRecoveryFailureById(options?: useDataConnectMutationOptions<RecordNotificationRecoveryFailureByIdData, FirebaseError, RecordNotificationRecoveryFailureByIdVariables>): UseDataConnectMutationResult<RecordNotificationRecoveryFailureByIdData, RecordNotificationRecoveryFailureByIdVariables>;
export function useRecordNotificationRecoveryFailureById(dc: DataConnect, options?: useDataConnectMutationOptions<RecordNotificationRecoveryFailureByIdData, FirebaseError, RecordNotificationRecoveryFailureByIdVariables>): UseDataConnectMutationResult<RecordNotificationRecoveryFailureByIdData, RecordNotificationRecoveryFailureByIdVariables>;

export function useMarkNotificationDeliverySentById(options?: useDataConnectMutationOptions<MarkNotificationDeliverySentByIdData, FirebaseError, MarkNotificationDeliverySentByIdVariables>): UseDataConnectMutationResult<MarkNotificationDeliverySentByIdData, MarkNotificationDeliverySentByIdVariables>;
export function useMarkNotificationDeliverySentById(dc: DataConnect, options?: useDataConnectMutationOptions<MarkNotificationDeliverySentByIdData, FirebaseError, MarkNotificationDeliverySentByIdVariables>): UseDataConnectMutationResult<MarkNotificationDeliverySentByIdData, MarkNotificationDeliverySentByIdVariables>;

export function useMarkNotificationDeliveryFailedById(options?: useDataConnectMutationOptions<MarkNotificationDeliveryFailedByIdData, FirebaseError, MarkNotificationDeliveryFailedByIdVariables>): UseDataConnectMutationResult<MarkNotificationDeliveryFailedByIdData, MarkNotificationDeliveryFailedByIdVariables>;
export function useMarkNotificationDeliveryFailedById(dc: DataConnect, options?: useDataConnectMutationOptions<MarkNotificationDeliveryFailedByIdData, FirebaseError, MarkNotificationDeliveryFailedByIdVariables>): UseDataConnectMutationResult<MarkNotificationDeliveryFailedByIdData, MarkNotificationDeliveryFailedByIdVariables>;

export function useMarkTicketOrderPaidFromWebhook(options?: useDataConnectMutationOptions<MarkTicketOrderPaidFromWebhookData, FirebaseError, MarkTicketOrderPaidFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderPaidFromWebhookData, MarkTicketOrderPaidFromWebhookVariables>;
export function useMarkTicketOrderPaidFromWebhook(dc: DataConnect, options?: useDataConnectMutationOptions<MarkTicketOrderPaidFromWebhookData, FirebaseError, MarkTicketOrderPaidFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderPaidFromWebhookData, MarkTicketOrderPaidFromWebhookVariables>;

export function useMarkTicketOrderFailedFromWebhook(options?: useDataConnectMutationOptions<MarkTicketOrderFailedFromWebhookData, FirebaseError, MarkTicketOrderFailedFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderFailedFromWebhookData, MarkTicketOrderFailedFromWebhookVariables>;
export function useMarkTicketOrderFailedFromWebhook(dc: DataConnect, options?: useDataConnectMutationOptions<MarkTicketOrderFailedFromWebhookData, FirebaseError, MarkTicketOrderFailedFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderFailedFromWebhookData, MarkTicketOrderFailedFromWebhookVariables>;

export function useMarkTicketOrderRefundedFromWebhook(options?: useDataConnectMutationOptions<MarkTicketOrderRefundedFromWebhookData, FirebaseError, MarkTicketOrderRefundedFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderRefundedFromWebhookData, MarkTicketOrderRefundedFromWebhookVariables>;
export function useMarkTicketOrderRefundedFromWebhook(dc: DataConnect, options?: useDataConnectMutationOptions<MarkTicketOrderRefundedFromWebhookData, FirebaseError, MarkTicketOrderRefundedFromWebhookVariables>): UseDataConnectMutationResult<MarkTicketOrderRefundedFromWebhookData, MarkTicketOrderRefundedFromWebhookVariables>;

export function useUpsertTicketOrderDisputeFromWebhook(options?: useDataConnectMutationOptions<UpsertTicketOrderDisputeFromWebhookData, FirebaseError, UpsertTicketOrderDisputeFromWebhookVariables>): UseDataConnectMutationResult<UpsertTicketOrderDisputeFromWebhookData, UpsertTicketOrderDisputeFromWebhookVariables>;
export function useUpsertTicketOrderDisputeFromWebhook(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertTicketOrderDisputeFromWebhookData, FirebaseError, UpsertTicketOrderDisputeFromWebhookVariables>): UseDataConnectMutationResult<UpsertTicketOrderDisputeFromWebhookData, UpsertTicketOrderDisputeFromWebhookVariables>;

export function useGetPaymentReconciliationExceptionByOrderAndType(vars: GetPaymentReconciliationExceptionByOrderAndTypeVariables, options?: useDataConnectQueryOptions<GetPaymentReconciliationExceptionByOrderAndTypeData>): UseDataConnectQueryResult<GetPaymentReconciliationExceptionByOrderAndTypeData, GetPaymentReconciliationExceptionByOrderAndTypeVariables>;
export function useGetPaymentReconciliationExceptionByOrderAndType(dc: DataConnect, vars: GetPaymentReconciliationExceptionByOrderAndTypeVariables, options?: useDataConnectQueryOptions<GetPaymentReconciliationExceptionByOrderAndTypeData>): UseDataConnectQueryResult<GetPaymentReconciliationExceptionByOrderAndTypeData, GetPaymentReconciliationExceptionByOrderAndTypeVariables>;

export function useUpsertPaymentReconciliationException(options?: useDataConnectMutationOptions<UpsertPaymentReconciliationExceptionData, FirebaseError, UpsertPaymentReconciliationExceptionVariables>): UseDataConnectMutationResult<UpsertPaymentReconciliationExceptionData, UpsertPaymentReconciliationExceptionVariables>;
export function useUpsertPaymentReconciliationException(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertPaymentReconciliationExceptionData, FirebaseError, UpsertPaymentReconciliationExceptionVariables>): UseDataConnectMutationResult<UpsertPaymentReconciliationExceptionData, UpsertPaymentReconciliationExceptionVariables>;

export function useUpdateBookingPreferencesFromCallable(options?: useDataConnectMutationOptions<UpdateBookingPreferencesFromCallableData, FirebaseError, UpdateBookingPreferencesFromCallableVariables>): UseDataConnectMutationResult<UpdateBookingPreferencesFromCallableData, UpdateBookingPreferencesFromCallableVariables>;
export function useUpdateBookingPreferencesFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateBookingPreferencesFromCallableData, FirebaseError, UpdateBookingPreferencesFromCallableVariables>): UseDataConnectMutationResult<UpdateBookingPreferencesFromCallableData, UpdateBookingPreferencesFromCallableVariables>;

export function useDeleteBookingLineFromCallable(options?: useDataConnectMutationOptions<DeleteBookingLineFromCallableData, FirebaseError, DeleteBookingLineFromCallableVariables>): UseDataConnectMutationResult<DeleteBookingLineFromCallableData, DeleteBookingLineFromCallableVariables>;
export function useDeleteBookingLineFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteBookingLineFromCallableData, FirebaseError, DeleteBookingLineFromCallableVariables>): UseDataConnectMutationResult<DeleteBookingLineFromCallableData, DeleteBookingLineFromCallableVariables>;

export function useCreateGuestTicketRequestFromCallable(options?: useDataConnectMutationOptions<CreateGuestTicketRequestFromCallableData, FirebaseError, CreateGuestTicketRequestFromCallableVariables>): UseDataConnectMutationResult<CreateGuestTicketRequestFromCallableData, CreateGuestTicketRequestFromCallableVariables>;
export function useCreateGuestTicketRequestFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<CreateGuestTicketRequestFromCallableData, FirebaseError, CreateGuestTicketRequestFromCallableVariables>): UseDataConnectMutationResult<CreateGuestTicketRequestFromCallableData, CreateGuestTicketRequestFromCallableVariables>;

export function useAdminReviewGuestTicketRequestFromCallable(options?: useDataConnectMutationOptions<AdminReviewGuestTicketRequestFromCallableData, FirebaseError, AdminReviewGuestTicketRequestFromCallableVariables>): UseDataConnectMutationResult<AdminReviewGuestTicketRequestFromCallableData, AdminReviewGuestTicketRequestFromCallableVariables>;
export function useAdminReviewGuestTicketRequestFromCallable(dc: DataConnect, options?: useDataConnectMutationOptions<AdminReviewGuestTicketRequestFromCallableData, FirebaseError, AdminReviewGuestTicketRequestFromCallableVariables>): UseDataConnectMutationResult<AdminReviewGuestTicketRequestFromCallableData, AdminReviewGuestTicketRequestFromCallableVariables>;

export function useGetBookingForGuestTicketCallable(vars: GetBookingForGuestTicketCallableVariables, options?: useDataConnectQueryOptions<GetBookingForGuestTicketCallableData>): UseDataConnectQueryResult<GetBookingForGuestTicketCallableData, GetBookingForGuestTicketCallableVariables>;
export function useGetBookingForGuestTicketCallable(dc: DataConnect, vars: GetBookingForGuestTicketCallableVariables, options?: useDataConnectQueryOptions<GetBookingForGuestTicketCallableData>): UseDataConnectQueryResult<GetBookingForGuestTicketCallableData, GetBookingForGuestTicketCallableVariables>;

export function useGetBookingForNotification(vars: GetBookingForNotificationVariables, options?: useDataConnectQueryOptions<GetBookingForNotificationData>): UseDataConnectQueryResult<GetBookingForNotificationData, GetBookingForNotificationVariables>;
export function useGetBookingForNotification(dc: DataConnect, vars: GetBookingForNotificationVariables, options?: useDataConnectQueryOptions<GetBookingForNotificationData>): UseDataConnectQueryResult<GetBookingForNotificationData, GetBookingForNotificationVariables>;

export function useListStaleDraftBookingsForScheduler(vars: ListStaleDraftBookingsForSchedulerVariables, options?: useDataConnectQueryOptions<ListStaleDraftBookingsForSchedulerData>): UseDataConnectQueryResult<ListStaleDraftBookingsForSchedulerData, ListStaleDraftBookingsForSchedulerVariables>;
export function useListStaleDraftBookingsForScheduler(dc: DataConnect, vars: ListStaleDraftBookingsForSchedulerVariables, options?: useDataConnectQueryOptions<ListStaleDraftBookingsForSchedulerData>): UseDataConnectQueryResult<ListStaleDraftBookingsForSchedulerData, ListStaleDraftBookingsForSchedulerVariables>;

export function useListStalePendingTicketOrdersForScheduler(vars: ListStalePendingTicketOrdersForSchedulerVariables, options?: useDataConnectQueryOptions<ListStalePendingTicketOrdersForSchedulerData>): UseDataConnectQueryResult<ListStalePendingTicketOrdersForSchedulerData, ListStalePendingTicketOrdersForSchedulerVariables>;
export function useListStalePendingTicketOrdersForScheduler(dc: DataConnect, vars: ListStalePendingTicketOrdersForSchedulerVariables, options?: useDataConnectQueryOptions<ListStalePendingTicketOrdersForSchedulerData>): UseDataConnectQueryResult<ListStalePendingTicketOrdersForSchedulerData, ListStalePendingTicketOrdersForSchedulerVariables>;

export function useGetGuestTicketRequestForNotification(vars: GetGuestTicketRequestForNotificationVariables, options?: useDataConnectQueryOptions<GetGuestTicketRequestForNotificationData>): UseDataConnectQueryResult<GetGuestTicketRequestForNotificationData, GetGuestTicketRequestForNotificationVariables>;
export function useGetGuestTicketRequestForNotification(dc: DataConnect, vars: GetGuestTicketRequestForNotificationVariables, options?: useDataConnectQueryOptions<GetGuestTicketRequestForNotificationData>): UseDataConnectQueryResult<GetGuestTicketRequestForNotificationData, GetGuestTicketRequestForNotificationVariables>;

export function useGetSectionAnnouncementOptOuts(vars: GetSectionAnnouncementOptOutsVariables, options?: useDataConnectQueryOptions<GetSectionAnnouncementOptOutsData>): UseDataConnectQueryResult<GetSectionAnnouncementOptOutsData, GetSectionAnnouncementOptOutsVariables>;
export function useGetSectionAnnouncementOptOuts(dc: DataConnect, vars: GetSectionAnnouncementOptOutsVariables, options?: useDataConnectQueryOptions<GetSectionAnnouncementOptOutsData>): UseDataConnectQueryResult<GetSectionAnnouncementOptOutsData, GetSectionAnnouncementOptOutsVariables>;

export function useCreateAnnouncementSend(options?: useDataConnectMutationOptions<CreateAnnouncementSendData, FirebaseError, CreateAnnouncementSendVariables>): UseDataConnectMutationResult<CreateAnnouncementSendData, CreateAnnouncementSendVariables>;
export function useCreateAnnouncementSend(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAnnouncementSendData, FirebaseError, CreateAnnouncementSendVariables>): UseDataConnectMutationResult<CreateAnnouncementSendData, CreateAnnouncementSendVariables>;

export function useCreateAnnouncementRecipient(options?: useDataConnectMutationOptions<CreateAnnouncementRecipientData, FirebaseError, CreateAnnouncementRecipientVariables>): UseDataConnectMutationResult<CreateAnnouncementRecipientData, CreateAnnouncementRecipientVariables>;
export function useCreateAnnouncementRecipient(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAnnouncementRecipientData, FirebaseError, CreateAnnouncementRecipientVariables>): UseDataConnectMutationResult<CreateAnnouncementRecipientData, CreateAnnouncementRecipientVariables>;

export function useGetAnnouncementRecipientCount(vars: GetAnnouncementRecipientCountVariables, options?: useDataConnectQueryOptions<GetAnnouncementRecipientCountData>): UseDataConnectQueryResult<GetAnnouncementRecipientCountData, GetAnnouncementRecipientCountVariables>;
export function useGetAnnouncementRecipientCount(dc: DataConnect, vars: GetAnnouncementRecipientCountVariables, options?: useDataConnectQueryOptions<GetAnnouncementRecipientCountData>): UseDataConnectQueryResult<GetAnnouncementRecipientCountData, GetAnnouncementRecipientCountVariables>;

export function useGetAnnouncementSendHistory(vars: GetAnnouncementSendHistoryVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendHistoryData>): UseDataConnectQueryResult<GetAnnouncementSendHistoryData, GetAnnouncementSendHistoryVariables>;
export function useGetAnnouncementSendHistory(dc: DataConnect, vars: GetAnnouncementSendHistoryVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendHistoryData>): UseDataConnectQueryResult<GetAnnouncementSendHistoryData, GetAnnouncementSendHistoryVariables>;

export function useGetAnnouncementSendRecipients(vars: GetAnnouncementSendRecipientsVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendRecipientsData>): UseDataConnectQueryResult<GetAnnouncementSendRecipientsData, GetAnnouncementSendRecipientsVariables>;
export function useGetAnnouncementSendRecipients(dc: DataConnect, vars: GetAnnouncementSendRecipientsVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendRecipientsData>): UseDataConnectQueryResult<GetAnnouncementSendRecipientsData, GetAnnouncementSendRecipientsVariables>;

export function useGetAnnouncementSendById(vars: GetAnnouncementSendByIdVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendByIdData>): UseDataConnectQueryResult<GetAnnouncementSendByIdData, GetAnnouncementSendByIdVariables>;
export function useGetAnnouncementSendById(dc: DataConnect, vars: GetAnnouncementSendByIdVariables, options?: useDataConnectQueryOptions<GetAnnouncementSendByIdData>): UseDataConnectQueryResult<GetAnnouncementSendByIdData, GetAnnouncementSendByIdVariables>;

export function useGetAnnouncementRecipientBySendAndUser(vars: GetAnnouncementRecipientBySendAndUserVariables, options?: useDataConnectQueryOptions<GetAnnouncementRecipientBySendAndUserData>): UseDataConnectQueryResult<GetAnnouncementRecipientBySendAndUserData, GetAnnouncementRecipientBySendAndUserVariables>;
export function useGetAnnouncementRecipientBySendAndUser(dc: DataConnect, vars: GetAnnouncementRecipientBySendAndUserVariables, options?: useDataConnectQueryOptions<GetAnnouncementRecipientBySendAndUserData>): UseDataConnectQueryResult<GetAnnouncementRecipientBySendAndUserData, GetAnnouncementRecipientBySendAndUserVariables>;

export function useTryUpdateAnnouncementRecipientDeliveryStatus(options?: useDataConnectMutationOptions<TryUpdateAnnouncementRecipientDeliveryStatusData, FirebaseError, TryUpdateAnnouncementRecipientDeliveryStatusVariables>): UseDataConnectMutationResult<TryUpdateAnnouncementRecipientDeliveryStatusData, TryUpdateAnnouncementRecipientDeliveryStatusVariables>;
export function useTryUpdateAnnouncementRecipientDeliveryStatus(dc: DataConnect, options?: useDataConnectMutationOptions<TryUpdateAnnouncementRecipientDeliveryStatusData, FirebaseError, TryUpdateAnnouncementRecipientDeliveryStatusVariables>): UseDataConnectMutationResult<TryUpdateAnnouncementRecipientDeliveryStatusData, TryUpdateAnnouncementRecipientDeliveryStatusVariables>;

export function useGetUserByEmail(vars: GetUserByEmailVariables, options?: useDataConnectQueryOptions<GetUserByEmailData>): UseDataConnectQueryResult<GetUserByEmailData, GetUserByEmailVariables>;
export function useGetUserByEmail(dc: DataConnect, vars: GetUserByEmailVariables, options?: useDataConnectQueryOptions<GetUserByEmailData>): UseDataConnectQueryResult<GetUserByEmailData, GetUserByEmailVariables>;

export function useGetNotifyCallbackUserById(vars: GetNotifyCallbackUserByIdVariables, options?: useDataConnectQueryOptions<GetNotifyCallbackUserByIdData>): UseDataConnectQueryResult<GetNotifyCallbackUserByIdData, GetNotifyCallbackUserByIdVariables>;
export function useGetNotifyCallbackUserById(dc: DataConnect, vars: GetNotifyCallbackUserByIdVariables, options?: useDataConnectQueryOptions<GetNotifyCallbackUserByIdData>): UseDataConnectQueryResult<GetNotifyCallbackUserByIdData, GetNotifyCallbackUserByIdVariables>;

export function useTryApplyNotifyDeliveryUserState(options?: useDataConnectMutationOptions<TryApplyNotifyDeliveryUserStateData, FirebaseError, TryApplyNotifyDeliveryUserStateVariables>): UseDataConnectMutationResult<TryApplyNotifyDeliveryUserStateData, TryApplyNotifyDeliveryUserStateVariables>;
export function useTryApplyNotifyDeliveryUserState(dc: DataConnect, options?: useDataConnectMutationOptions<TryApplyNotifyDeliveryUserStateData, FirebaseError, TryApplyNotifyDeliveryUserStateVariables>): UseDataConnectMutationResult<TryApplyNotifyDeliveryUserStateData, TryApplyNotifyDeliveryUserStateVariables>;

export function useTryApplyNotifyDeliveryUserStateAndMarkLost(options?: useDataConnectMutationOptions<TryApplyNotifyDeliveryUserStateAndMarkLostData, FirebaseError, TryApplyNotifyDeliveryUserStateAndMarkLostVariables>): UseDataConnectMutationResult<TryApplyNotifyDeliveryUserStateAndMarkLostData, TryApplyNotifyDeliveryUserStateAndMarkLostVariables>;
export function useTryApplyNotifyDeliveryUserStateAndMarkLost(dc: DataConnect, options?: useDataConnectMutationOptions<TryApplyNotifyDeliveryUserStateAndMarkLostData, FirebaseError, TryApplyNotifyDeliveryUserStateAndMarkLostVariables>): UseDataConnectMutationResult<TryApplyNotifyDeliveryUserStateAndMarkLostData, TryApplyNotifyDeliveryUserStateAndMarkLostVariables>;

export function useGetNotifyDeliveryReceipt(vars: GetNotifyDeliveryReceiptVariables, options?: useDataConnectQueryOptions<GetNotifyDeliveryReceiptData>): UseDataConnectQueryResult<GetNotifyDeliveryReceiptData, GetNotifyDeliveryReceiptVariables>;
export function useGetNotifyDeliveryReceipt(dc: DataConnect, vars: GetNotifyDeliveryReceiptVariables, options?: useDataConnectQueryOptions<GetNotifyDeliveryReceiptData>): UseDataConnectQueryResult<GetNotifyDeliveryReceiptData, GetNotifyDeliveryReceiptVariables>;

export function useCreateNotifyDeliveryReceipt(options?: useDataConnectMutationOptions<CreateNotifyDeliveryReceiptData, FirebaseError, CreateNotifyDeliveryReceiptVariables>): UseDataConnectMutationResult<CreateNotifyDeliveryReceiptData, CreateNotifyDeliveryReceiptVariables>;
export function useCreateNotifyDeliveryReceipt(dc: DataConnect, options?: useDataConnectMutationOptions<CreateNotifyDeliveryReceiptData, FirebaseError, CreateNotifyDeliveryReceiptVariables>): UseDataConnectMutationResult<CreateNotifyDeliveryReceiptData, CreateNotifyDeliveryReceiptVariables>;

export function useClaimNotifyDeliveryReceipt(options?: useDataConnectMutationOptions<ClaimNotifyDeliveryReceiptData, FirebaseError, ClaimNotifyDeliveryReceiptVariables>): UseDataConnectMutationResult<ClaimNotifyDeliveryReceiptData, ClaimNotifyDeliveryReceiptVariables>;
export function useClaimNotifyDeliveryReceipt(dc: DataConnect, options?: useDataConnectMutationOptions<ClaimNotifyDeliveryReceiptData, FirebaseError, ClaimNotifyDeliveryReceiptVariables>): UseDataConnectMutationResult<ClaimNotifyDeliveryReceiptData, ClaimNotifyDeliveryReceiptVariables>;

export function useMarkNotifyDeliveryReceiptProcessed(options?: useDataConnectMutationOptions<MarkNotifyDeliveryReceiptProcessedData, FirebaseError, MarkNotifyDeliveryReceiptProcessedVariables>): UseDataConnectMutationResult<MarkNotifyDeliveryReceiptProcessedData, MarkNotifyDeliveryReceiptProcessedVariables>;
export function useMarkNotifyDeliveryReceiptProcessed(dc: DataConnect, options?: useDataConnectMutationOptions<MarkNotifyDeliveryReceiptProcessedData, FirebaseError, MarkNotifyDeliveryReceiptProcessedVariables>): UseDataConnectMutationResult<MarkNotifyDeliveryReceiptProcessedData, MarkNotifyDeliveryReceiptProcessedVariables>;

export function useMarkNotifyDeliveryReceiptFailed(options?: useDataConnectMutationOptions<MarkNotifyDeliveryReceiptFailedData, FirebaseError, MarkNotifyDeliveryReceiptFailedVariables>): UseDataConnectMutationResult<MarkNotifyDeliveryReceiptFailedData, MarkNotifyDeliveryReceiptFailedVariables>;
export function useMarkNotifyDeliveryReceiptFailed(dc: DataConnect, options?: useDataConnectMutationOptions<MarkNotifyDeliveryReceiptFailedData, FirebaseError, MarkNotifyDeliveryReceiptFailedVariables>): UseDataConnectMutationResult<MarkNotifyDeliveryReceiptFailedData, MarkNotifyDeliveryReceiptFailedVariables>;

export function useGetRecentNotifyDeliveryReceiptsForUser(vars: GetRecentNotifyDeliveryReceiptsForUserVariables, options?: useDataConnectQueryOptions<GetRecentNotifyDeliveryReceiptsForUserData>): UseDataConnectQueryResult<GetRecentNotifyDeliveryReceiptsForUserData, GetRecentNotifyDeliveryReceiptsForUserVariables>;
export function useGetRecentNotifyDeliveryReceiptsForUser(dc: DataConnect, vars: GetRecentNotifyDeliveryReceiptsForUserVariables, options?: useDataConnectQueryOptions<GetRecentNotifyDeliveryReceiptsForUserData>): UseDataConnectQueryResult<GetRecentNotifyDeliveryReceiptsForUserData, GetRecentNotifyDeliveryReceiptsForUserVariables>;

export function useGetLatestNotifyDeliveryReceiptForReference(vars: GetLatestNotifyDeliveryReceiptForReferenceVariables, options?: useDataConnectQueryOptions<GetLatestNotifyDeliveryReceiptForReferenceData>): UseDataConnectQueryResult<GetLatestNotifyDeliveryReceiptForReferenceData, GetLatestNotifyDeliveryReceiptForReferenceVariables>;
export function useGetLatestNotifyDeliveryReceiptForReference(dc: DataConnect, vars: GetLatestNotifyDeliveryReceiptForReferenceVariables, options?: useDataConnectQueryOptions<GetLatestNotifyDeliveryReceiptForReferenceData>): UseDataConnectQueryResult<GetLatestNotifyDeliveryReceiptForReferenceData, GetLatestNotifyDeliveryReceiptForReferenceVariables>;

export function useAdminOptOutSectionAnnouncement(options?: useDataConnectMutationOptions<AdminOptOutSectionAnnouncementData, FirebaseError, AdminOptOutSectionAnnouncementVariables>): UseDataConnectMutationResult<AdminOptOutSectionAnnouncementData, AdminOptOutSectionAnnouncementVariables>;
export function useAdminOptOutSectionAnnouncement(dc: DataConnect, options?: useDataConnectMutationOptions<AdminOptOutSectionAnnouncementData, FirebaseError, AdminOptOutSectionAnnouncementVariables>): UseDataConnectMutationResult<AdminOptOutSectionAnnouncementData, AdminOptOutSectionAnnouncementVariables>;

export function useAdminOptInSectionAnnouncement(options?: useDataConnectMutationOptions<AdminOptInSectionAnnouncementData, FirebaseError, AdminOptInSectionAnnouncementVariables>): UseDataConnectMutationResult<AdminOptInSectionAnnouncementData, AdminOptInSectionAnnouncementVariables>;
export function useAdminOptInSectionAnnouncement(dc: DataConnect, options?: useDataConnectMutationOptions<AdminOptInSectionAnnouncementData, FirebaseError, AdminOptInSectionAnnouncementVariables>): UseDataConnectMutationResult<AdminOptInSectionAnnouncementData, AdminOptInSectionAnnouncementVariables>;

export function useGetCallableInvocation(vars: GetCallableInvocationVariables, options?: useDataConnectQueryOptions<GetCallableInvocationData>): UseDataConnectQueryResult<GetCallableInvocationData, GetCallableInvocationVariables>;
export function useGetCallableInvocation(dc: DataConnect, vars: GetCallableInvocationVariables, options?: useDataConnectQueryOptions<GetCallableInvocationData>): UseDataConnectQueryResult<GetCallableInvocationData, GetCallableInvocationVariables>;

export function useUpsertCallableInvocation(options?: useDataConnectMutationOptions<UpsertCallableInvocationData, FirebaseError, UpsertCallableInvocationVariables>): UseDataConnectMutationResult<UpsertCallableInvocationData, UpsertCallableInvocationVariables>;
export function useUpsertCallableInvocation(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertCallableInvocationData, FirebaseError, UpsertCallableInvocationVariables>): UseDataConnectMutationResult<UpsertCallableInvocationData, UpsertCallableInvocationVariables>;

export function useEnsureCallableRateLimitBucket(options?: useDataConnectMutationOptions<EnsureCallableRateLimitBucketData, FirebaseError, EnsureCallableRateLimitBucketVariables>): UseDataConnectMutationResult<EnsureCallableRateLimitBucketData, EnsureCallableRateLimitBucketVariables>;
export function useEnsureCallableRateLimitBucket(dc: DataConnect, options?: useDataConnectMutationOptions<EnsureCallableRateLimitBucketData, FirebaseError, EnsureCallableRateLimitBucketVariables>): UseDataConnectMutationResult<EnsureCallableRateLimitBucketData, EnsureCallableRateLimitBucketVariables>;

export function useConsumeCallableRateLimit(options?: useDataConnectMutationOptions<ConsumeCallableRateLimitData, FirebaseError, ConsumeCallableRateLimitVariables>): UseDataConnectMutationResult<ConsumeCallableRateLimitData, ConsumeCallableRateLimitVariables>;
export function useConsumeCallableRateLimit(dc: DataConnect, options?: useDataConnectMutationOptions<ConsumeCallableRateLimitData, FirebaseError, ConsumeCallableRateLimitVariables>): UseDataConnectMutationResult<ConsumeCallableRateLimitData, ConsumeCallableRateLimitVariables>;

export function useCreateBookingDraft(options?: useDataConnectMutationOptions<CreateBookingDraftData, FirebaseError, CreateBookingDraftVariables>): UseDataConnectMutationResult<CreateBookingDraftData, CreateBookingDraftVariables>;
export function useCreateBookingDraft(dc: DataConnect, options?: useDataConnectMutationOptions<CreateBookingDraftData, FirebaseError, CreateBookingDraftVariables>): UseDataConnectMutationResult<CreateBookingDraftData, CreateBookingDraftVariables>;

export function useAddBookingLine(options?: useDataConnectMutationOptions<AddBookingLineData, FirebaseError, AddBookingLineVariables>): UseDataConnectMutationResult<AddBookingLineData, AddBookingLineVariables>;
export function useAddBookingLine(dc: DataConnect, options?: useDataConnectMutationOptions<AddBookingLineData, FirebaseError, AddBookingLineVariables>): UseDataConnectMutationResult<AddBookingLineData, AddBookingLineVariables>;

export function useUpdateBookingStatus(options?: useDataConnectMutationOptions<UpdateBookingStatusData, FirebaseError, UpdateBookingStatusVariables>): UseDataConnectMutationResult<UpdateBookingStatusData, UpdateBookingStatusVariables>;
export function useUpdateBookingStatus(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateBookingStatusData, FirebaseError, UpdateBookingStatusVariables>): UseDataConnectMutationResult<UpdateBookingStatusData, UpdateBookingStatusVariables>;

export function useCreateGuestTicketRequest(options?: useDataConnectMutationOptions<CreateGuestTicketRequestData, FirebaseError, CreateGuestTicketRequestVariables>): UseDataConnectMutationResult<CreateGuestTicketRequestData, CreateGuestTicketRequestVariables>;
export function useCreateGuestTicketRequest(dc: DataConnect, options?: useDataConnectMutationOptions<CreateGuestTicketRequestData, FirebaseError, CreateGuestTicketRequestVariables>): UseDataConnectMutationResult<CreateGuestTicketRequestData, CreateGuestTicketRequestVariables>;

export function useAdminDeleteGuestTicketRequest(options?: useDataConnectMutationOptions<AdminDeleteGuestTicketRequestData, FirebaseError, AdminDeleteGuestTicketRequestVariables>): UseDataConnectMutationResult<AdminDeleteGuestTicketRequestData, AdminDeleteGuestTicketRequestVariables>;
export function useAdminDeleteGuestTicketRequest(dc: DataConnect, options?: useDataConnectMutationOptions<AdminDeleteGuestTicketRequestData, FirebaseError, AdminDeleteGuestTicketRequestVariables>): UseDataConnectMutationResult<AdminDeleteGuestTicketRequestData, AdminDeleteGuestTicketRequestVariables>;

export function useAdminReviewGuestTicketRequest(options?: useDataConnectMutationOptions<AdminReviewGuestTicketRequestData, FirebaseError, AdminReviewGuestTicketRequestVariables>): UseDataConnectMutationResult<AdminReviewGuestTicketRequestData, AdminReviewGuestTicketRequestVariables>;
export function useAdminReviewGuestTicketRequest(dc: DataConnect, options?: useDataConnectMutationOptions<AdminReviewGuestTicketRequestData, FirebaseError, AdminReviewGuestTicketRequestVariables>): UseDataConnectMutationResult<AdminReviewGuestTicketRequestData, AdminReviewGuestTicketRequestVariables>;

export function useAdminDeleteBookingLine(options?: useDataConnectMutationOptions<AdminDeleteBookingLineData, FirebaseError, AdminDeleteBookingLineVariables>): UseDataConnectMutationResult<AdminDeleteBookingLineData, AdminDeleteBookingLineVariables>;
export function useAdminDeleteBookingLine(dc: DataConnect, options?: useDataConnectMutationOptions<AdminDeleteBookingLineData, FirebaseError, AdminDeleteBookingLineVariables>): UseDataConnectMutationResult<AdminDeleteBookingLineData, AdminDeleteBookingLineVariables>;

export function useAdminDeleteBooking(options?: useDataConnectMutationOptions<AdminDeleteBookingData, FirebaseError, AdminDeleteBookingVariables>): UseDataConnectMutationResult<AdminDeleteBookingData, AdminDeleteBookingVariables>;
export function useAdminDeleteBooking(dc: DataConnect, options?: useDataConnectMutationOptions<AdminDeleteBookingData, FirebaseError, AdminDeleteBookingVariables>): UseDataConnectMutationResult<AdminDeleteBookingData, AdminDeleteBookingVariables>;

export function useResolvePaymentReconciliationException(options?: useDataConnectMutationOptions<ResolvePaymentReconciliationExceptionData, FirebaseError, ResolvePaymentReconciliationExceptionVariables>): UseDataConnectMutationResult<ResolvePaymentReconciliationExceptionData, ResolvePaymentReconciliationExceptionVariables>;
export function useResolvePaymentReconciliationException(dc: DataConnect, options?: useDataConnectMutationOptions<ResolvePaymentReconciliationExceptionData, FirebaseError, ResolvePaymentReconciliationExceptionVariables>): UseDataConnectMutationResult<ResolvePaymentReconciliationExceptionData, ResolvePaymentReconciliationExceptionVariables>;

export function useGetCurrentUser(options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;
export function useGetCurrentUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;

export function useGetUserById(vars: GetUserByIdVariables, options?: useDataConnectQueryOptions<GetUserByIdData>): UseDataConnectQueryResult<GetUserByIdData, GetUserByIdVariables>;
export function useGetUserById(dc: DataConnect, vars: GetUserByIdVariables, options?: useDataConnectQueryOptions<GetUserByIdData>): UseDataConnectQueryResult<GetUserByIdData, GetUserByIdVariables>;

export function useListUsers(options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;
export function useListUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;

export function useListSections(options?: useDataConnectQueryOptions<ListSectionsData>): UseDataConnectQueryResult<ListSectionsData, undefined>;
export function useListSections(dc: DataConnect, options?: useDataConnectQueryOptions<ListSectionsData>): UseDataConnectQueryResult<ListSectionsData, undefined>;

export function useGetSectionsForUser(options?: useDataConnectQueryOptions<GetSectionsForUserData>): UseDataConnectQueryResult<GetSectionsForUserData, undefined>;
export function useGetSectionsForUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetSectionsForUserData>): UseDataConnectQueryResult<GetSectionsForUserData, undefined>;

export function useListUserGroups(options?: useDataConnectQueryOptions<ListUserGroupsData>): UseDataConnectQueryResult<ListUserGroupsData, undefined>;
export function useListUserGroups(dc: DataConnect, options?: useDataConnectQueryOptions<ListUserGroupsData>): UseDataConnectQueryResult<ListUserGroupsData, undefined>;

export function useGetUserAccessGroups(options?: useDataConnectQueryOptions<GetUserAccessGroupsData>): UseDataConnectQueryResult<GetUserAccessGroupsData, undefined>;
export function useGetUserAccessGroups(dc: DataConnect, options?: useDataConnectQueryOptions<GetUserAccessGroupsData>): UseDataConnectQueryResult<GetUserAccessGroupsData, undefined>;

export function useCheckUserProfileExists(options?: useDataConnectQueryOptions<CheckUserProfileExistsData>): UseDataConnectQueryResult<CheckUserProfileExistsData, undefined>;
export function useCheckUserProfileExists(dc: DataConnect, options?: useDataConnectQueryOptions<CheckUserProfileExistsData>): UseDataConnectQueryResult<CheckUserProfileExistsData, undefined>;

export function useGetUserMembershipStatus(vars: GetUserMembershipStatusVariables, options?: useDataConnectQueryOptions<GetUserMembershipStatusData>): UseDataConnectQueryResult<GetUserMembershipStatusData, GetUserMembershipStatusVariables>;
export function useGetUserMembershipStatus(dc: DataConnect, vars: GetUserMembershipStatusVariables, options?: useDataConnectQueryOptions<GetUserMembershipStatusData>): UseDataConnectQueryResult<GetUserMembershipStatusData, GetUserMembershipStatusVariables>;

export function useGetUserWithAccessGroups(vars: GetUserWithAccessGroupsVariables, options?: useDataConnectQueryOptions<GetUserWithAccessGroupsData>): UseDataConnectQueryResult<GetUserWithAccessGroupsData, GetUserWithAccessGroupsVariables>;
export function useGetUserWithAccessGroups(dc: DataConnect, vars: GetUserWithAccessGroupsVariables, options?: useDataConnectQueryOptions<GetUserWithAccessGroupsData>): UseDataConnectQueryResult<GetUserWithAccessGroupsData, GetUserWithAccessGroupsVariables>;

export function useGetUserAccessGroupsById(vars: GetUserAccessGroupsByIdVariables, options?: useDataConnectQueryOptions<GetUserAccessGroupsByIdData>): UseDataConnectQueryResult<GetUserAccessGroupsByIdData, GetUserAccessGroupsByIdVariables>;
export function useGetUserAccessGroupsById(dc: DataConnect, vars: GetUserAccessGroupsByIdVariables, options?: useDataConnectQueryOptions<GetUserAccessGroupsByIdData>): UseDataConnectQueryResult<GetUserAccessGroupsByIdData, GetUserAccessGroupsByIdVariables>;

export function useGetEventsForSection(vars: GetEventsForSectionVariables, options?: useDataConnectQueryOptions<GetEventsForSectionData>): UseDataConnectQueryResult<GetEventsForSectionData, GetEventsForSectionVariables>;
export function useGetEventsForSection(dc: DataConnect, vars: GetEventsForSectionVariables, options?: useDataConnectQueryOptions<GetEventsForSectionData>): UseDataConnectQueryResult<GetEventsForSectionData, GetEventsForSectionVariables>;

export function useGetEventById(vars: GetEventByIdVariables, options?: useDataConnectQueryOptions<GetEventByIdData>): UseDataConnectQueryResult<GetEventByIdData, GetEventByIdVariables>;
export function useGetEventById(dc: DataConnect, vars: GetEventByIdVariables, options?: useDataConnectQueryOptions<GetEventByIdData>): UseDataConnectQueryResult<GetEventByIdData, GetEventByIdVariables>;

export function useGetSectionById(vars: GetSectionByIdVariables, options?: useDataConnectQueryOptions<GetSectionByIdData>): UseDataConnectQueryResult<GetSectionByIdData, GetSectionByIdVariables>;
export function useGetSectionById(dc: DataConnect, vars: GetSectionByIdVariables, options?: useDataConnectQueryOptions<GetSectionByIdData>): UseDataConnectQueryResult<GetSectionByIdData, GetSectionByIdVariables>;

export function useGetUserGroupById(vars: GetUserGroupByIdVariables, options?: useDataConnectQueryOptions<GetUserGroupByIdData>): UseDataConnectQueryResult<GetUserGroupByIdData, GetUserGroupByIdVariables>;
export function useGetUserGroupById(dc: DataConnect, vars: GetUserGroupByIdVariables, options?: useDataConnectQueryOptions<GetUserGroupByIdData>): UseDataConnectQueryResult<GetUserGroupByIdData, GetUserGroupByIdVariables>;

export function useGetAllUserGroupsWithStatuses(options?: useDataConnectQueryOptions<GetAllUserGroupsWithStatusesData>): UseDataConnectQueryResult<GetAllUserGroupsWithStatusesData, undefined>;
export function useGetAllUserGroupsWithStatuses(dc: DataConnect, options?: useDataConnectQueryOptions<GetAllUserGroupsWithStatusesData>): UseDataConnectQueryResult<GetAllUserGroupsWithStatusesData, undefined>;

export function useGetSectionMembers(vars: GetSectionMembersVariables, options?: useDataConnectQueryOptions<GetSectionMembersData>): UseDataConnectQueryResult<GetSectionMembersData, GetSectionMembersVariables>;
export function useGetSectionMembers(dc: DataConnect, vars: GetSectionMembersVariables, options?: useDataConnectQueryOptions<GetSectionMembersData>): UseDataConnectQueryResult<GetSectionMembersData, GetSectionMembersVariables>;

export function useGetMyBookingsForEvent(vars: GetMyBookingsForEventVariables, options?: useDataConnectQueryOptions<GetMyBookingsForEventData>): UseDataConnectQueryResult<GetMyBookingsForEventData, GetMyBookingsForEventVariables>;
export function useGetMyBookingsForEvent(dc: DataConnect, vars: GetMyBookingsForEventVariables, options?: useDataConnectQueryOptions<GetMyBookingsForEventData>): UseDataConnectQueryResult<GetMyBookingsForEventData, GetMyBookingsForEventVariables>;

export function useGetMyBookings(options?: useDataConnectQueryOptions<GetMyBookingsData>): UseDataConnectQueryResult<GetMyBookingsData, undefined>;
export function useGetMyBookings(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyBookingsData>): UseDataConnectQueryResult<GetMyBookingsData, undefined>;

export function useGetMyTicketOrderById(vars: GetMyTicketOrderByIdVariables, options?: useDataConnectQueryOptions<GetMyTicketOrderByIdData>): UseDataConnectQueryResult<GetMyTicketOrderByIdData, GetMyTicketOrderByIdVariables>;
export function useGetMyTicketOrderById(dc: DataConnect, vars: GetMyTicketOrderByIdVariables, options?: useDataConnectQueryOptions<GetMyTicketOrderByIdData>): UseDataConnectQueryResult<GetMyTicketOrderByIdData, GetMyTicketOrderByIdVariables>;

export function useGetMyTicketOrders(options?: useDataConnectQueryOptions<GetMyTicketOrdersData>): UseDataConnectQueryResult<GetMyTicketOrdersData, undefined>;
export function useGetMyTicketOrders(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyTicketOrdersData>): UseDataConnectQueryResult<GetMyTicketOrdersData, undefined>;

export function useGetMyBookingPaymentAdjustments(options?: useDataConnectQueryOptions<GetMyBookingPaymentAdjustmentsData>): UseDataConnectQueryResult<GetMyBookingPaymentAdjustmentsData, undefined>;
export function useGetMyBookingPaymentAdjustments(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyBookingPaymentAdjustmentsData>): UseDataConnectQueryResult<GetMyBookingPaymentAdjustmentsData, undefined>;

export function useListEventBookingsForAdmin(vars: ListEventBookingsForAdminVariables, options?: useDataConnectQueryOptions<ListEventBookingsForAdminData>): UseDataConnectQueryResult<ListEventBookingsForAdminData, ListEventBookingsForAdminVariables>;
export function useListEventBookingsForAdmin(dc: DataConnect, vars: ListEventBookingsForAdminVariables, options?: useDataConnectQueryOptions<ListEventBookingsForAdminData>): UseDataConnectQueryResult<ListEventBookingsForAdminData, ListEventBookingsForAdminVariables>;

export function useListGuestTicketRequestsForAdmin(vars: ListGuestTicketRequestsForAdminVariables, options?: useDataConnectQueryOptions<ListGuestTicketRequestsForAdminData>): UseDataConnectQueryResult<ListGuestTicketRequestsForAdminData, ListGuestTicketRequestsForAdminVariables>;
export function useListGuestTicketRequestsForAdmin(dc: DataConnect, vars: ListGuestTicketRequestsForAdminVariables, options?: useDataConnectQueryOptions<ListGuestTicketRequestsForAdminData>): UseDataConnectQueryResult<ListGuestTicketRequestsForAdminData, ListGuestTicketRequestsForAdminVariables>;

export function useListTicketOrdersForAdmin(vars: ListTicketOrdersForAdminVariables, options?: useDataConnectQueryOptions<ListTicketOrdersForAdminData>): UseDataConnectQueryResult<ListTicketOrdersForAdminData, ListTicketOrdersForAdminVariables>;
export function useListTicketOrdersForAdmin(dc: DataConnect, vars: ListTicketOrdersForAdminVariables, options?: useDataConnectQueryOptions<ListTicketOrdersForAdminData>): UseDataConnectQueryResult<ListTicketOrdersForAdminData, ListTicketOrdersForAdminVariables>;

export function useListBookingPaymentAdjustmentsForAdmin(vars: ListBookingPaymentAdjustmentsForAdminVariables, options?: useDataConnectQueryOptions<ListBookingPaymentAdjustmentsForAdminData>): UseDataConnectQueryResult<ListBookingPaymentAdjustmentsForAdminData, ListBookingPaymentAdjustmentsForAdminVariables>;
export function useListBookingPaymentAdjustmentsForAdmin(dc: DataConnect, vars: ListBookingPaymentAdjustmentsForAdminVariables, options?: useDataConnectQueryOptions<ListBookingPaymentAdjustmentsForAdminData>): UseDataConnectQueryResult<ListBookingPaymentAdjustmentsForAdminData, ListBookingPaymentAdjustmentsForAdminVariables>;

export function useListOpenPaymentReconciliationExceptions(options?: useDataConnectQueryOptions<ListOpenPaymentReconciliationExceptionsData>): UseDataConnectQueryResult<ListOpenPaymentReconciliationExceptionsData, undefined>;
export function useListOpenPaymentReconciliationExceptions(dc: DataConnect, options?: useDataConnectQueryOptions<ListOpenPaymentReconciliationExceptionsData>): UseDataConnectQueryResult<ListOpenPaymentReconciliationExceptionsData, undefined>;

export function useGetSectionAnnouncementOptOut(vars: GetSectionAnnouncementOptOutVariables, options?: useDataConnectQueryOptions<GetSectionAnnouncementOptOutData>): UseDataConnectQueryResult<GetSectionAnnouncementOptOutData, GetSectionAnnouncementOptOutVariables>;
export function useGetSectionAnnouncementOptOut(dc: DataConnect, vars: GetSectionAnnouncementOptOutVariables, options?: useDataConnectQueryOptions<GetSectionAnnouncementOptOutData>): UseDataConnectQueryResult<GetSectionAnnouncementOptOutData, GetSectionAnnouncementOptOutVariables>;

export function useGetMyAnnouncementPreferences(options?: useDataConnectQueryOptions<GetMyAnnouncementPreferencesData>): UseDataConnectQueryResult<GetMyAnnouncementPreferencesData, undefined>;
export function useGetMyAnnouncementPreferences(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyAnnouncementPreferencesData>): UseDataConnectQueryResult<GetMyAnnouncementPreferencesData, undefined>;

export function useCreateSection(options?: useDataConnectMutationOptions<CreateSectionData, FirebaseError, CreateSectionVariables>): UseDataConnectMutationResult<CreateSectionData, CreateSectionVariables>;
export function useCreateSection(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSectionData, FirebaseError, CreateSectionVariables>): UseDataConnectMutationResult<CreateSectionData, CreateSectionVariables>;

export function useCreateUserGroup(options?: useDataConnectMutationOptions<CreateUserGroupData, FirebaseError, CreateUserGroupVariables>): UseDataConnectMutationResult<CreateUserGroupData, CreateUserGroupVariables>;
export function useCreateUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserGroupData, FirebaseError, CreateUserGroupVariables>): UseDataConnectMutationResult<CreateUserGroupData, CreateUserGroupVariables>;

export function useAddUserToUserGroup(options?: useDataConnectMutationOptions<AddUserToUserGroupData, FirebaseError, AddUserToUserGroupVariables>): UseDataConnectMutationResult<AddUserToUserGroupData, AddUserToUserGroupVariables>;
export function useAddUserToUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<AddUserToUserGroupData, FirebaseError, AddUserToUserGroupVariables>): UseDataConnectMutationResult<AddUserToUserGroupData, AddUserToUserGroupVariables>;

export function useRemoveUserFromUserGroup(options?: useDataConnectMutationOptions<RemoveUserFromUserGroupData, FirebaseError, RemoveUserFromUserGroupVariables>): UseDataConnectMutationResult<RemoveUserFromUserGroupData, RemoveUserFromUserGroupVariables>;
export function useRemoveUserFromUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveUserFromUserGroupData, FirebaseError, RemoveUserFromUserGroupVariables>): UseDataConnectMutationResult<RemoveUserFromUserGroupData, RemoveUserFromUserGroupVariables>;

export function useGrantUserGroupToSectionForPurpose(options?: useDataConnectMutationOptions<GrantUserGroupToSectionForPurposeData, FirebaseError, GrantUserGroupToSectionForPurposeVariables>): UseDataConnectMutationResult<GrantUserGroupToSectionForPurposeData, GrantUserGroupToSectionForPurposeVariables>;
export function useGrantUserGroupToSectionForPurpose(dc: DataConnect, options?: useDataConnectMutationOptions<GrantUserGroupToSectionForPurposeData, FirebaseError, GrantUserGroupToSectionForPurposeVariables>): UseDataConnectMutationResult<GrantUserGroupToSectionForPurposeData, GrantUserGroupToSectionForPurposeVariables>;

export function useRevokeUserGroupFromSectionForPurpose(options?: useDataConnectMutationOptions<RevokeUserGroupFromSectionForPurposeData, FirebaseError, RevokeUserGroupFromSectionForPurposeVariables>): UseDataConnectMutationResult<RevokeUserGroupFromSectionForPurposeData, RevokeUserGroupFromSectionForPurposeVariables>;
export function useRevokeUserGroupFromSectionForPurpose(dc: DataConnect, options?: useDataConnectMutationOptions<RevokeUserGroupFromSectionForPurposeData, FirebaseError, RevokeUserGroupFromSectionForPurposeVariables>): UseDataConnectMutationResult<RevokeUserGroupFromSectionForPurposeData, RevokeUserGroupFromSectionForPurposeVariables>;

export function useUpdateUserGroup(options?: useDataConnectMutationOptions<UpdateUserGroupData, FirebaseError, UpdateUserGroupVariables>): UseDataConnectMutationResult<UpdateUserGroupData, UpdateUserGroupVariables>;
export function useUpdateUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserGroupData, FirebaseError, UpdateUserGroupVariables>): UseDataConnectMutationResult<UpdateUserGroupData, UpdateUserGroupVariables>;

export function useDeleteUserGroup(options?: useDataConnectMutationOptions<DeleteUserGroupData, FirebaseError, DeleteUserGroupVariables>): UseDataConnectMutationResult<DeleteUserGroupData, DeleteUserGroupVariables>;
export function useDeleteUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteUserGroupData, FirebaseError, DeleteUserGroupVariables>): UseDataConnectMutationResult<DeleteUserGroupData, DeleteUserGroupVariables>;

export function useUpdateSection(options?: useDataConnectMutationOptions<UpdateSectionData, FirebaseError, UpdateSectionVariables>): UseDataConnectMutationResult<UpdateSectionData, UpdateSectionVariables>;
export function useUpdateSection(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSectionData, FirebaseError, UpdateSectionVariables>): UseDataConnectMutationResult<UpdateSectionData, UpdateSectionVariables>;

export function useDeleteSection(options?: useDataConnectMutationOptions<DeleteSectionData, FirebaseError, DeleteSectionVariables>): UseDataConnectMutationResult<DeleteSectionData, DeleteSectionVariables>;
export function useDeleteSection(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteSectionData, FirebaseError, DeleteSectionVariables>): UseDataConnectMutationResult<DeleteSectionData, DeleteSectionVariables>;

export function useCreateEvent(options?: useDataConnectMutationOptions<CreateEventData, FirebaseError, CreateEventVariables>): UseDataConnectMutationResult<CreateEventData, CreateEventVariables>;
export function useCreateEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEventData, FirebaseError, CreateEventVariables>): UseDataConnectMutationResult<CreateEventData, CreateEventVariables>;

export function useUpdateEvent(options?: useDataConnectMutationOptions<UpdateEventData, FirebaseError, UpdateEventVariables>): UseDataConnectMutationResult<UpdateEventData, UpdateEventVariables>;
export function useUpdateEvent(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEventData, FirebaseError, UpdateEventVariables>): UseDataConnectMutationResult<UpdateEventData, UpdateEventVariables>;

export function useDeleteEvent(options?: useDataConnectMutationOptions<DeleteEventData, FirebaseError, DeleteEventVariables>): UseDataConnectMutationResult<DeleteEventData, DeleteEventVariables>;
export function useDeleteEvent(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteEventData, FirebaseError, DeleteEventVariables>): UseDataConnectMutationResult<DeleteEventData, DeleteEventVariables>;

export function useCreateTicketType(options?: useDataConnectMutationOptions<CreateTicketTypeData, FirebaseError, CreateTicketTypeVariables>): UseDataConnectMutationResult<CreateTicketTypeData, CreateTicketTypeVariables>;
export function useCreateTicketType(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTicketTypeData, FirebaseError, CreateTicketTypeVariables>): UseDataConnectMutationResult<CreateTicketTypeData, CreateTicketTypeVariables>;

export function useUpdateTicketType(options?: useDataConnectMutationOptions<UpdateTicketTypeData, FirebaseError, UpdateTicketTypeVariables>): UseDataConnectMutationResult<UpdateTicketTypeData, UpdateTicketTypeVariables>;
export function useUpdateTicketType(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTicketTypeData, FirebaseError, UpdateTicketTypeVariables>): UseDataConnectMutationResult<UpdateTicketTypeData, UpdateTicketTypeVariables>;

export function useDeleteTicketType(options?: useDataConnectMutationOptions<DeleteTicketTypeData, FirebaseError, DeleteTicketTypeVariables>): UseDataConnectMutationResult<DeleteTicketTypeData, DeleteTicketTypeVariables>;
export function useDeleteTicketType(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTicketTypeData, FirebaseError, DeleteTicketTypeVariables>): UseDataConnectMutationResult<DeleteTicketTypeData, DeleteTicketTypeVariables>;

export function useCreateUserProfile(options?: useDataConnectMutationOptions<CreateUserProfileData, FirebaseError, CreateUserProfileVariables>): UseDataConnectMutationResult<CreateUserProfileData, CreateUserProfileVariables>;
export function useCreateUserProfile(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserProfileData, FirebaseError, CreateUserProfileVariables>): UseDataConnectMutationResult<CreateUserProfileData, CreateUserProfileVariables>;

export function useUpsertUser(options?: useDataConnectMutationOptions<UpsertUserData, FirebaseError, UpsertUserVariables>): UseDataConnectMutationResult<UpsertUserData, UpsertUserVariables>;
export function useUpsertUser(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertUserData, FirebaseError, UpsertUserVariables>): UseDataConnectMutationResult<UpsertUserData, UpsertUserVariables>;

export function useUpdateUser(options?: useDataConnectMutationOptions<UpdateUserData, FirebaseError, UpdateUserVariables>): UseDataConnectMutationResult<UpdateUserData, UpdateUserVariables>;
export function useUpdateUser(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserData, FirebaseError, UpdateUserVariables>): UseDataConnectMutationResult<UpdateUserData, UpdateUserVariables>;

export function useRegisterForSection(options?: useDataConnectMutationOptions<RegisterForSectionData, FirebaseError, RegisterForSectionVariables>): UseDataConnectMutationResult<RegisterForSectionData, RegisterForSectionVariables>;
export function useRegisterForSection(dc: DataConnect, options?: useDataConnectMutationOptions<RegisterForSectionData, FirebaseError, RegisterForSectionVariables>): UseDataConnectMutationResult<RegisterForSectionData, RegisterForSectionVariables>;

export function useUnregisterFromSection(options?: useDataConnectMutationOptions<UnregisterFromSectionData, FirebaseError, UnregisterFromSectionVariables>): UseDataConnectMutationResult<UnregisterFromSectionData, UnregisterFromSectionVariables>;
export function useUnregisterFromSection(dc: DataConnect, options?: useDataConnectMutationOptions<UnregisterFromSectionData, FirebaseError, UnregisterFromSectionVariables>): UseDataConnectMutationResult<UnregisterFromSectionData, UnregisterFromSectionVariables>;

export function useSubscribeToUserGroup(options?: useDataConnectMutationOptions<SubscribeToUserGroupData, FirebaseError, SubscribeToUserGroupVariables>): UseDataConnectMutationResult<SubscribeToUserGroupData, SubscribeToUserGroupVariables>;
export function useSubscribeToUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<SubscribeToUserGroupData, FirebaseError, SubscribeToUserGroupVariables>): UseDataConnectMutationResult<SubscribeToUserGroupData, SubscribeToUserGroupVariables>;

export function useUnsubscribeFromUserGroup(options?: useDataConnectMutationOptions<UnsubscribeFromUserGroupData, FirebaseError, UnsubscribeFromUserGroupVariables>): UseDataConnectMutationResult<UnsubscribeFromUserGroupData, UnsubscribeFromUserGroupVariables>;
export function useUnsubscribeFromUserGroup(dc: DataConnect, options?: useDataConnectMutationOptions<UnsubscribeFromUserGroupData, FirebaseError, UnsubscribeFromUserGroupVariables>): UseDataConnectMutationResult<UnsubscribeFromUserGroupData, UnsubscribeFromUserGroupVariables>;

export function useOptOutSectionAnnouncement(options?: useDataConnectMutationOptions<OptOutSectionAnnouncementData, FirebaseError, OptOutSectionAnnouncementVariables>): UseDataConnectMutationResult<OptOutSectionAnnouncementData, OptOutSectionAnnouncementVariables>;
export function useOptOutSectionAnnouncement(dc: DataConnect, options?: useDataConnectMutationOptions<OptOutSectionAnnouncementData, FirebaseError, OptOutSectionAnnouncementVariables>): UseDataConnectMutationResult<OptOutSectionAnnouncementData, OptOutSectionAnnouncementVariables>;

export function useOptInSectionAnnouncement(options?: useDataConnectMutationOptions<OptInSectionAnnouncementData, FirebaseError, OptInSectionAnnouncementVariables>): UseDataConnectMutationResult<OptInSectionAnnouncementData, OptInSectionAnnouncementVariables>;
export function useOptInSectionAnnouncement(dc: DataConnect, options?: useDataConnectMutationOptions<OptInSectionAnnouncementData, FirebaseError, OptInSectionAnnouncementVariables>): UseDataConnectMutationResult<OptInSectionAnnouncementData, OptInSectionAnnouncementVariables>;
